### ISSUE TITLE
Training script stuck at Building main

### ISSUE THREAD

**Issue by jaggernaut007** [anibali/margipose#12]
The docker compose build seems to be stuck at building main . This has been stuck for more than two hours now. have restarted this many times thinking it ws stuck.. How long does it usually take. i am running it on the Intel Xeon processor, with V100 GPU.

**Comment by jaggernaut007** [comment]
Fixed this. Changed the .dockerignore file! phew.

**Comment by anibali** [comment]
For anyone reading this in the future, a common reason for this is having one or more datasets located in the same directory as the rest of the project files (eg if you create a `datasets/` directory as a sibling of `Dockerfile` and prepare datasets in there). This will cause Docker to add all of the dataset files to the "build context" when building the Docker image, which is completely unnecessary and extremely time-consuming. To solve this, either move the dataset files somewhere else in your filesystem or add the dataset directory (eg the line `/datasets/`) to `.dockerignore`.
