### ISSUE TITLE
Looking for a speed up

### ISSUE THREAD

**Issue by jaggernaut007** [anibali/margipose#14]
Margipose is quite an accurate model, does some great detections! Kudos to the team!!
I am looking to speed up the model, for fast inference. 
Its currently running at a speed of 2-3 FPS for inference on my 1080. 
The best way to speed up I have in mind would be to reduce the res of input and use the resnet 18 model. 
Resnet 18 wouldnt make a lot of difference keeping in mind the model architechture.
Is there any other way? 
Thanks!

**Comment by anibali** [comment]
It's also possible to simply reduce the number of stacks. The pretrained models I've made available have 4 stacks, but you could try reducing that to maybe 2 and see if that reaches a better accuracy/speed trade-off.

If you do try ResNet-18 or find some other sweet spot for performance, please report back here---I'd love to hear your results.

**Comment by jaggernaut007** [comment]
Yup, the stacks can be reduced. 
For a baseline, let me move to resnet18 and reduce stack. 
Lots of performance gain strategies to try out!
Ill update the results here.

**Comment by guker** [comment]
> Yup, the stacks can be reduced.
> For a baseline, let me move to resnet18 and reduce stack.
> Lots of performance gain strategies to try out!
> Ill update the results here.

@jaggernaut007  how much faster than original margipose using your resnet18?

**Comment by Tomiha** [comment]
> Yup, the stacks can be reduced.
> For a baseline, let me move to resnet18 and reduce stack.
> Lots of performance gain strategies to try out!
> Ill update the results here.

Same question as @guker :)
