### ISSUE TITLE
Error of run test_onnx.py 

### ISSUE THREAD

**Issue by www516717402** [anibali/margipose#16]
Great project. Thank you for share.
When I run test_onnx.py with param: `feature_extractor='resnet50'`, Conv layer channels error. I am looking for the reason.

**Comment by anibali** [comment]
The 'resnet50' feature_extractor option was broken due to a mismatched number of feature maps. Fixed in https://github.com/anibali/margipose/commit/e96d59187dc17651ab184ca263f9a1a150cfa201.
