### ISSUE TITLE
how prediction convert to camera coordination in inference phase？

### ISSUE THREAD

**Issue by guker** [anibali/margipose#19]
Now，I have a video，no camera intrinsics， so how i can convert prediction to camera coordination in inference phase？

**Comment by anibali** [comment]
The camera intrinsics are required for that step of the process, so you will need to make a rough guess of what the intrinsics could be. Otherwise you are stuck with the predicted coordinates in normalised space.

**Comment by guker** [comment]
https://github.com/anibali/pose3d-utils/blob/8ecab2c9c842d7a41c59f01cb8d00fd3166bb3e0/pose3d_utils/skeleton_normaliser.py#L119

In other words，i can assume suitable camera intrinsics，and combine [infer_depth](https://github.com/anibali/pose3d-utils/blob/8ecab2c9c842d7a41c59f01cb8d00fd3166bb3e0/pose3d_utils/skeleton_normaliser.py#L119) ，then convert prediction to camera space， right？

**Comment by anibali** [comment]
Yep. You can use one of these functions to get the `eval_scale` function parameter:

https://github.com/anibali/margipose/blob/e96d59187dc17651ab184ca263f9a1a150cfa201/src/margipose/data/skeleton.py#L196-L213

**Comment by guker** [comment]
got it， thanks very much！

**Comment by guker** [comment]
> got it， thanks very much！

it works well

**Comment by sunmengnan** [comment]
![image](https://user-images.githubusercontent.com/30337134/140853267-f2bd4de3-e96a-4130-9e9b-875b1dea88d7.png)
Is the depth predicted here in infer_single.py(step in utils, it is each joint? ) in 2d space, not 3d camera space?

**Comment by anibali** [comment]
I believe that the breakpoint that you are looking at in your debugger corresponds to this line in `infer_single.py`:

https://github.com/anibali/margipose/blob/2933f30203b3cd5c636917a7c9ff107d02434598/src/margipose/bin/infer_single.py#L75

At this point the joints (`norm_skel3d`) exist in **normalised 3D space**. Further up in this issue you can see discussion around denormalising (recovering metric units).

**Comment by sunmengnan** [comment]
Yes...the key is how to denormalise it,  shoule I use PoseDataset.denormalise in data/__init__.py? But I don't have the value of untransform in eval_scale...
