### ISSUE TITLE
Are the provided preprocessing codes for MPI-INF-3DHP based on corrected labels?

### ISSUE THREAD

**Issue by cherryjm** [anibali/margipose#25]
Hi, thank you for your work!
I've noticed that in your paper, there are two versions of MPI-INF-3DHP dataset, i.e. uncorrected labels and corrected labels. Are the provided preprocessing codes for MPI-INF-3DHP based on corrected labels? Or could you please tell me how to correct labels? Thank you very much.

**Comment by anibali** [comment]
I believe that the authors of the dataset only make the latest version of the test set labels available, so if you downloaded it recently you should have the corrected labels.

**Comment by cherryjm** [comment]
Got it! Thank you for your reply.
