### ISSUE TITLE
[ Volumetric Heatmaps Dimension ]

### ISSUE THREAD

**Issue by IemProg** [anibali/margipose#26]
Hi, 

What's the dimensions of the of heatmaps before _**permute**_ function in **_down_layers_** block, Is it **[Batch_size, Joints, Depth, Height, Width ]** ?

if that's the case how can we apply permutation if number of joints is not the same as width, it will raise dimentionality mismatch given that you have applied permutation of: 

`mid_out = torch.cat([t.permute(0, 3, 2, 1) for t in mid_in.split(size, -3)], -3)`

What does **"C" letter** refer to in _Figure 5_ of the paper, please ?

Thanks !

**Comment by anibali** [comment]
"c" is the number of channels for the intermediate features, which must be a multiple of the height/width. Note that the number of joints is not one of the dimensions (these are intermediate features, not heatmaps).

So the size of `mid_in` is `[batch_size, c, height, width]` where height = width and c is a multiple of width.
