### ISSUE TITLE
Evaluation code is not compatible with h36m dataset

### ISSUE THREAD

**Issue by hoyeYang** [anibali/margipose#3]
Hi, thanks for your great contribution!
However, when I evaluated on h36m dataset, an error occurred in line 84 of the eval_3d.py since 'frame_ref' is only used in mpi3d dataset

**Comment by anibali** [comment]
It looks like I broke the evaluation code for Human3.6M in this commit: https://github.com/anibali/margipose/commit/8d798d7dfc11cf7450b25538bf8df6192efcd1cb. I'll look into fixing it again.

**Comment by anibali** [comment]
This issue should be fixed in https://github.com/anibali/margipose/commit/65649a5ddc8577546f3006d0d58c31b4087fd306. Please give it a try.

**Comment by hoyeYang** [comment]
It works now.
Thanks!
