### ISSUE TITLE
No module named 'pose3d_utils'

### ISSUE THREAD

**Issue by sunmengnan** [anibali/margipose#30]
when i run preprocess_mpi3d.py, No module named 'pose3d_utils'. Should I install it from another repo?

**Comment by anibali** [comment]
Please refer to the requirements listed in https://github.com/anibali/margipose/blob/master/requirements.txt

That individual package can be installed with:

```console
pip install git+https://github.com/anibali/pose3d-utils@9251f832d9b7aa38e1e5b592965e5f557317ec36#egg=pose3d-utils
```

**Comment by sunmengnan** [comment]
> Please refer to the requirements listed in https://github.com/anibali/margipose/blob/master/requirements.txt
> 
> That individual package can be installed with:
> 
> ```
> pip install git+https://github.com/anibali/pose3d-utils@9251f832d9b7aa38e1e5b592965e5f557317ec36#egg=pose3d-utils
> ```

Thx. can I infer the model on windows?

**Comment by anibali** [comment]
I haven't tried it myself, but I can't think of any particular reason why it wouldn't work. You'll have to test it out for yourself :)
