### ISSUE TITLE
Expected input image dimensions for MargiPose

### ISSUE THREAD

**Issue by sunmengnan** [anibali/margipose#33]
when inferring on my own imgs, RuntimeError: Given groups=1, weight of size 192 192 3 3, expected input[1, 384, 4, 4] to have 192 channels, but got 384 channels instead. Any idea how to fix it?

**Comment by anibali** [comment]
What is the shape of the input tensor that you are feeding into the model?

**Comment by sunmengnan** [comment]
> What is the shape of the input tensor that you are feeding into the model?

It is 3x116x55

**Comment by anibali** [comment]
Please resize and pad your input to match the expected input dimensions of the model. Refer to `infer_single.py`:

https://github.com/anibali/margipose/blob/master/src/margipose/bin/infer_single.py#L58-L66

**Comment by sunmengnan** [comment]
> Please resize and pad your input to match the expected input dimensions of the model. Refer to `infer_single.py`:
> 
> https://github.com/anibali/margipose/blob/master/src/margipose/bin/infer_single.py#L58-L66

Does the input shape has to be 3x256x256?

**Comment by anibali** [comment]
That size is guaranteed to work, I think that other spatial dimensions could result in rounding errors. Also, make sure that you add a batch dimension (even if it is just 1). So your input should be 1x3x256x256. Again, refer to the script.

**Comment by sunmengnan** [comment]
> That size is guaranteed to work, I think that other spatial dimensions could result in rounding errors. Also, make sure that you add a batch dimension (even if it is just 1). So your input should be 1x3x256x256. Again, refer to the script.

Thank you for your help. Closing...
